spring:
  application:
    name: supplier-gateway
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    virtual-host: /
grpc:
  host: ${GRPC_HOST:localhost}
  port: ${GRPC_PORT:50051}
server:
  port: ${SERVER_PORT:8082}
rabbit:
  queue: ${RABBIT_QUEUE:eventQueue}
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    enable:
      all: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
